services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    ports:
      - "6379:6379"

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    command: redis-server --replicaof redis-node1 6379
    ports:
      - "6380:6379"

  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.12
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"